# MOwNiT 
## Laboratorium
## Wybrane zagadnienia algebry liniowej, faktoryzacja
### Algebra liniowa w Julii
https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/index.html

In [1]:
using(LinearAlgebra)

In [2]:
methods(factorize)

# 11 methods for generic function "factorize":
[1] factorize(A::Union{DenseArray{T,2}, Base.ReinterpretArray{T,2,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, Base.ReshapedArray{T,2,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray}, SubArray{T,2,A,I,L} where L where I<:Tuple{Vararg{Union{Int64, AbstractRange{Int64}, Base.AbstractCartesianIndex},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, Base.ReshapedArray{T,N,A,MI} where MI<:Tuple{Vararg{Base.MultiplicativeInverses.SignedMultiplicativeInverse{Int64},N} where N} where A<:Union{Base.ReinterpretArray{T,N,S,A} where S where A<:Union{SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, SubArray{T,N,A,I,true} where I<:Union{Tuple{Vararg{Real,N} where N}, Tuple{AbstractUnitRange,Vararg{Any,N} where N}} where A<:DenseArray where N where T, DenseArray} where N where T, DenseArray}}) where T in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\dense.jl:1197
[2] factorize(A::Adjoint) in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\dense.jl:1272
[3] factorize(A::Transpose) in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\dense.jl:1273
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\triangular.jl:2547
[5] factorize(A::Union{Hermitian{Complex{Float64},#s627}, Hermitian{Float64,#s627}, Symmetric{Float64,#s627}} where #s627<:SparseArrays.SparseMatrixCSC) in SparseArrays at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\SparseArrays\src\linalg.jl:1493
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S) where T in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\symmetric.jl:499
[7] factorize(A::Tridiagonal) in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\lu.jl:559
[8] factorize(D::Diagonal) in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\bidiag.jl:765
[10] factorize(S::SymTridiagonal) in LinearAlgebra at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\LinearAlgebra\src\ldlt.jl:124
[11] factorize(A::SparseArrays.SparseMatrixCSC) in SparseArrays at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.3\SparseArrays\src\linalg.jl:1463

In [3]:
#wiersze vs kolumny
x1=[1 2 2]

1×3 Array{Int64,2}:
 1  2  2

In [4]:
y1=[1 ;2 ;3]

3-element Array{Int64,1}:
 1
 2
 3

In [5]:
transpose(x1)

3×1 Transpose{Int64,Array{Int64,2}}:
 1
 2
 2

In [6]:
#iloczyn skalarny
dot(x1,y1)

11

 Długość wektora liczymy jako pierwiastek z jego iloczynu skalarnego 
$$ \lVert\mathbf{v}\rVert = \sqrt{\mathbf{v}\cdot \mathbf{v}}=\sqrt{\sum_{i=1}^nv_i^2}$$



#### Przykładowe dane

In [9]:
#losujemy macierz 3x3
A=rand(3,3)

3×3 Array{Float64,2}:
 0.0598385  0.905314  0.152162
 0.580851   0.862735  0.622782
 0.52767    0.344275  0.715301

In [10]:
#losujemy wektor x
x=rand(3)

3-element Array{Float64,1}:
 0.02959796807420978
 0.6782665078889007 
 0.06152411468480268

In [11]:
# wyliczamy b
b=A*x

3-element Array{Float64,1}:
 0.6251770621877955
 0.6406722045069437
 0.2931363355907788

### Sposoby rozwiązania Ax=b

In [12]:
#mozemy policzyc odwrotność macierzy i wymnożyć
# uwaga: nieefektywne!
inv(A) * b

3-element Array{Float64,1}:
 0.02959796807420889
 0.6782665078889007 
 0.06152411468480401

In [13]:
#najlepiej używać zoptymalizowanego operatora "\""
x=A\b

3-element Array{Float64,1}:
 0.02959796807420877 
 0.6782665078889006  
 0.061524114684803656

 operator "\\" wybiera odpowiednią faktoryzację:
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#LinearAlgebra.factorize
- https://docs.julialang.org/en/v1.2/stdlib/LinearAlgebra/#man-linalg-factorizations-1
 


### Faktoryzacja LU

In [14]:
# W przypadku ogólnej macierzy kwadratowej jest to faktoryzacja LU z pivotem
Af=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.103019   1.0       0.0
 0.908443  -0.538278  1.0
U factor:
3×3 Array{Float64,2}:
 0.580851  0.862735  0.622782 
 0.0       0.816437  0.0880038
 0.0       0.0       0.19691  

In [15]:
# Macierz L
Af.L

3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.103019   1.0       0.0
 0.908443  -0.538278  1.0

In [16]:
#Macierz U
Af.U

3×3 Array{Float64,2}:
 0.580851  0.862735  0.622782 
 0.0       0.816437  0.0880038
 0.0       0.0       0.19691  

In [17]:
# wektor permulatacji 
Af.p

3-element Array{Int64,1}:
 2
 1
 3

In [20]:
Af.L*Af.U

3×3 Array{Float64,2}:
 0.580851   0.862735  0.622782
 0.0598385  0.905314  0.152162
 0.52767    0.344275  0.715301

In [21]:
A

3×3 Array{Float64,2}:
 0.0598385  0.905314  0.152162
 0.580851   0.862735  0.622782
 0.52767    0.344275  0.715301

In [18]:
# to jest spełnione
Af.L*Af.U==A[Af.p,:]

true

In [22]:
# mozemy zamienic macierz A na postać zfaktoryzowaną
A=factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
3×3 Array{Float64,2}:
 1.0        0.0       0.0
 0.103019   1.0       0.0
 0.908443  -0.538278  1.0
U factor:
3×3 Array{Float64,2}:
 0.580851  0.862735  0.622782 
 0.0       0.816437  0.0880038
 0.0       0.0       0.19691  

In [23]:
# i działać na niej operatorem \
# operator ten będzie wykorzytywał raz utworzony wynik faktoryzacji
A\b

3-element Array{Float64,1}:
 0.02959796807420877 
 0.6782665078889006  
 0.061524114684803656

In [24]:
# dla różnych prawych stron równania z tą samą macierzą
c=rand(3);
A\c

3-element Array{Float64,1}:
 -0.16266044949196137
  0.36339247279263065
  0.21075098511449475

### Faktoryzacja QR


In [27]:
B=rand(5,10)

5×10 Array{Float64,2}:
 0.746859  0.403268   0.974654  0.88992   …  0.619073  0.0448308  0.484896
 0.635112  0.262924   0.239     0.416461     0.253279  0.1466     0.274578
 0.962255  0.0496622  0.97125   0.892406     0.282718  0.611513   0.964211
 0.280136  0.0815327  0.504812  0.185289     0.237621  0.16841    0.49849 
 0.350578  0.263851   0.674083  0.148859     0.680521  0.50543    0.783489

In [28]:
# W przypadku ogólnej macierzy prostokątnej wybierana jest faktoryzacja QR z pivotem
factorize(B)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
5×5 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.597641   0.138982   -0.489962    0.594543    0.173104
 -0.146551  -0.663287    0.0746987  -0.139357    0.71664 
 -0.595554  -0.0921714  -0.248134   -0.689777   -0.315367
 -0.309542  -0.493923    0.51711     0.376371   -0.501164
 -0.413336   0.536916    0.652215   -0.0982339   0.325331
R factor:
5×10 Array{Float64,2}:
 -1.63083  -1.15103   -1.20195     …  -0.443415   -1.24324    -1.38242  
  0.0      -0.683862  -0.00812407     -0.0215293  -0.246398   -0.0291528
  0.0       0.0        0.556035        0.0239803  -0.433451    0.312454 
  0.0       0.0        0.0             0.173632   -0.0893876  -0.304411 
  0.0       0.0        0.0             0.287545    0.126634   -0.0183009
permutation:
10-element Array{Int64,1}:
  3
  5
  6
  9
  8
  1
  7
  2
  4
 10

- $Q$ to macierz  ortogonalna mxm, co oznacza, że  $Q^T*Q=Q*Q^T=I$ czyli $Q^{-1}=Q^T$ (odwracanie takich macierzy jest szybkie i nie generuje dodatkowych błędów !)
- $R$ to macierz postaci $\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} $ , gdzie $Rfactor$ jest macierzą trójkątną górną, a 0 to macierz zer o wymierze nx(m-n)

### Zastosowanie faktoryzacji do metody najmniejszych kwadratów

Jednym z zastosowań faktoryzacji QR jest użycie jej do metody najmniejszych kwadratów.

Przykład:

Obliczmy dopasowanie wielomianu $$f(x)=wsp_2*x^2+wsp_1*x+wsp_0$$ do punktów (1,1) (2,2) (3,4) (4, 4) (5,3) (6,0)

- Budujemy układ równań wg wzoru $$wsp_2x_i^2+wsp_1x_i+wsp_0=y_i$$:
$$wsp_2*1^2+wsp_1*1+wsp_0=1$$
$$wsp_2*2^2+wsp_1*2+wsp_0=2$$
$$wsp_2*3^2+wsp_1*3+wsp_0=4$$
$$wsp_2*4^2+wsp_1*4+wsp_0=4$$
$$wsp_2*5^2+wsp_1*5+wsp_0=3$$
$$wsp_2*6^2+wsp_1*6+wsp_0=0$$

- Układ ten  nie ma dokładnego rozwiązania. Możemy jednak znaleźć najlepsze przybliżenie, czyli takie $wsp_i$, które minimalizują odległość:

$$\sqrt{\sum_{i=1}^{6}{(y_i-f(x_i))^2}}=\lVert y-A*wsp\rVert$$





Jak użyć do tej mimalizacji faktoryzacji QR:

#### 1. Tworzymy macierz A na postawie $(x_i,y_i)$

In [32]:
A=zeros(6,3) 

6×3 Array{Float64,2}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

 punkty $(x_i,y_i)$


In [33]:
x=[1; 2 ;3 ;4 ;5 ;6]
y=[1; 2; 4; 4; 3; 0]

6-element Array{Int64,1}:
 1
 2
 4
 4
 3
 0

In [34]:
A[:,1]=x.^2

6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [35]:
A[:,2]=x

6-element Array{Int64,1}:
 1
 2
 3
 4
 5
 6

In [36]:
A[:,3]=ones(6)

6-element Array{Float64,1}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [37]:
A

6×3 Array{Float64,2}:
  1.0  1.0  1.0
  4.0  2.0  1.0
  9.0  3.0  1.0
 16.0  4.0  1.0
 25.0  5.0  1.0
 36.0  6.0  1.0

#### 2. Dokonujemy faktoryzacji QR macierzy A 

In [38]:
 AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
6×6 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.0209657  -0.343313    0.838525   0.112335    -0.0400677  -0.405397
 -0.0838628  -0.521522    0.167705  -0.00636667   0.34634     0.756879
 -0.188691   -0.534625   -0.223607  -0.612934    -0.487947   -0.121617
 -0.335451   -0.382624   -0.33541    0.753648    -0.213523   -0.122449
 -0.524142   -0.0655178  -0.167705  -0.204705     0.705864   -0.390779
 -0.754765    0.416693    0.279508  -0.0419783   -0.310667    0.283364
R factor:
3×3 Array{Float64,2}:
 -47.697  -9.24587  -1.90788 
   0.0    -2.34816  -1.43091 
   0.0     0.0       0.559017
permutation:
3-element Array{Int64,1}:
 1
 2
 3

In [39]:
# można przetestować ortogonalność:
Transpose(AF.Q)*AF.Q

6×6 Array{Float64,2}:
  1.0           0.0           1.11022e-16  …   8.32667e-17   0.0        
  0.0           1.0           9.71445e-17     -5.55112e-17  -1.249e-16  
  1.11022e-16   9.71445e-17   1.0             -4.16334e-17   0.0        
 -9.71445e-17   3.46945e-17   2.60209e-17     -9.88792e-17  -2.08167e-17
  8.32667e-17  -5.55112e-17  -4.16334e-17      1.0           0.0        
  0.0          -1.249e-16     0.0          …   0.0           1.0        

Mamy równanie:
$$A*wsp=y$$
Dla $A=QR$:
$$QR*wsp =y$$
Możemy obydwie strony wymnożyć z lewej przez $Q^T$:
$$R*wsp =Q^T y$$
$$\begin{pmatrix} Rfactor \\ 0 \end{pmatrix} wsp= Q^T y$$

Poszukiwanym rozwiązaniem jest rozwiązanie równania będącego górną niezerową częścią:
$$Rfactor * wsp= Q^T y[1:n]$$
$$wsp=Rfactor \setminus Q^T y[1:n]$$

In [40]:
# implementacja powyższego (uwaga: w tym przykladzie nie jest potrzebna permutacja,
# bo wektor permutacji wynosi[1 2 3])
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
 -0.5714285714285727
  3.942857142857152 
 -2.8000000000000163

Więcej informacji:
- http://www.math.uconn.edu/~leykekhman/courses/MATH3795/Lectures/Lecture_8_Linear_least_squares_orthogonal_matrices.pdf
- http://www.seas.ucla.edu/~vandenbe/133A/lectures/qr.pdf

W praktyce używamy tego algorytmu poprzez operator "\\", za którym jest on "schowany".

In [41]:
A \ y

3-element Array{Float64,1}:
 -0.5714285714285726
  3.942857142857151 
 -2.8000000000000145

In [42]:
#sprawdzamy czy dostaliśmy dobre wspólczynniki
using Polynomials
polyfit(x,y, 2)

Poly(-2.8000000000000145 + 3.942857142857151*x - 0.5714285714285726*x^2)

Funkcja <a href="https://github.com/JuliaMath/Polynomials.jl/blob/ef129b779d08f791eb607e390ca9d31d8c08ead1/src/Polynomials.jl#L689-L707">
polyfit</a> używa własnie tej metody


### Zadania

#### Zadanie 1 
Ustal losowe (referencyjne) x rozmiaru 1000 oraz losowe A rozmiaru 1000x1000, policz b=A*x.
Nastepnie rozwiąż równanie Ax=b trzema metodami:
- inv()
- \
- factorize()

Porównaj jakość wyniku (zmierzoną jako długość różnicy wektorów wyniku oraz referencyjnego x) oraz czas wykonania (@time). UWAGA: pierwsze wykonanie funkcji w Julii zawiera czas kompilacji tej funkcji, dlatego czas mierzymy  od drugiego wywołania !

#### Zadanie 2
Policz współczynniki wielomianu aproksymującego dowolne dane z poprzednich laboratoriów tworząc wprost układ równań i rozwiązujac go (metoda zaprezentowana na tym laboratorium).
Porównaj wyniki z tymi otrzymanymi poprzednio.

#### Zadanie 3

Znajdź i zaprezentuj działanie innego zastosowania wybranej faktoryzacji. Przykładowe (ale nie jedyne!) tematy:

-    tworzenie pseudoinversji macierzy (http://buzzard.ups.edu/courses/2014spring/420projects/math420-UPS-spring-2014-macausland-pseudo-inverse-present.pdf).

-   uzycie faktoryzacji QR do znajdowania wartości własnych (https://en.wikipedia.org/wiki/QR_algorithm)

-  zastosowanie faktoryzacji SVD - przykład zastosowania w uczeniu maszynowym https://blog.statsbot.co/singular-value-decomposition-tutorial-52c695315254


